### ISSUE TITLE
scrollEl option not working in the latest version

### ISSUE THREAD

**Issue by pitAlex** [dollarshaveclub/stickybits#122]
Hi,

In the latest vesion(2.02) the scrollEl option is broken. I've inspected the code and it looks like in some areas its expected as a string while in others its expected as a dom element. Also I've noticed se.requestAnimationFrame  and it should be window.requestAnimationFrame because this method is only available in the window object and se can be window or scrollEl

**Comment by yowainwright** [comment]
Hey @pitAlex,

Thanks for your response! 

I’m happy to work on this with you.😊

There are tests and examples for the `scrollEl` feature in this repo that communicate to me that the feature is working. Maybe I/we can update tests to catch your notes in this issue?

—

### Quick thoughts

-  In regards to rAF, it is stubbed for when rAF is not supported—so that _should_ work. Does the stub not work?
-  don vs string—I changed from `node` to `string` so if there is anywhere that is still expecting a node than that is a problem that should be fixed. I/we should also document that.

—

Could you send some live code or pictures? (You could refer to the scrollEl codepen in the readme for fast sharing)

—

*\ This is a response is from a phone.

**Comment by pitAlex** [comment]
Well I am using the npm version and spotted this in the dist/ scripts folder. All I did was:
Sticky(element, {scrollEl : document.querySelector('#scroller')});
and
Sticky(element, {scrollEl : '#scroller'});

both throw errors as soon as the page is loaded in a browser that does not support position:sticky.

And also you should start making tests in Samsung Internet Browser since they made this to be the default browser of samsung devices and many users will not change it. We've been seeing in it in our sentry logs and its already causing problems all over the place.(HATE SAMSUNG!)

**Comment by yowainwright** [comment]
@pitAlex okay, great to know (about Samsung)—perhaps you could help maintain that support?

I'm looking for a way to make sure I'm fully understanding your issue. 😬

Could we use [this example](https://codepen.io/yowainwright/pen/EXzJeb) pulled directly from the [readme](https://github.com/dollarshaveclub/stickybits/blob/master/README.md) to normalize what we're discussing?

To further normalize our discussion: the psuedo code examples in your last comment are slightly incorrect. 

This should generally be how a custom scroll element should work.
```javascript
stickybits('selector', {scrollEl: 'selection'})
// in this psuedo code example:
// note that stickybits is not written as a constructor and
// that the name is `stickybits`
```
~ Thanks!

**Comment by pitAlex** [comment]
Yea sorry, I copied it from my code where I assigned stickybits to "Sticky". I had as you said,  but then switched to constructor when I was looking in the source code and starting doing debugging for the scrollEl. 
Now for the requestAnimationFrame. Its checked against "se" which is not always the window, thats the mistake. Support should be checked against the window.

**Comment by yowainwright** [comment]
@pitAlex 

```javascript
if (typeof rAF !== 'undefined' || !it.isWin) {
    rAF = function rAFDummy(f) {
      f()
    }
  }
```

Thoughts?
