### ISSUE TITLE
jumpy on IE, should be smooth and provide a fake vertical space on the DOM

### ISSUE THREAD

**Issue by oussa** [dollarshaveclub/stickybits#131]
Hello,

When trying the [official demo](https://dollarshaveclub.github.io/stickybits/) on IE, and scrolling very slowly, you can notice that when the nav moves from the _original position_ to _fixed to top_, it doesn't provide a fake space on the DOM to cover for its disappearance, consequently causing the _weird jump_.

To explain further this is how it looks like just before scrolling a little bit
![before jump](https://user-images.githubusercontent.com/4229227/31438843-28d56944-ae8a-11e7-8481-b996c157f28b.png)

and directly after the scroll..
![after jump](https://user-images.githubusercontent.com/4229227/31438842-2849dafa-ae8a-11e7-8e7a-67dac5cea5dc.png)

**Comment by yowainwright** [comment]
Which version of IE?

I don't see the problem in the screen captures provided. Perhaps you could provide an animated gif?

~Thanks

**Comment by oussa** [comment]
IE11 on Win7, tried it on BrowserStack first, and then to make sure it's not just my eyes or the frame-rate, I tried it locally. Here is an animated GIF with the problem.

![stickybits-issue-ie11-win7](https://user-images.githubusercontent.com/4229227/31456446-16eacc1c-aeba-11e7-9d01-54302a7ed88b.gif)

**Comment by yowainwright** [comment]
@oussa Would you like to fix that? 

If not—I'm going to close this issue. ~Thanks!

**Comment by yowainwright** [comment]
@oussa if you want to fix what you've noted go ahead and open this issue back up! ~Thanks!!!

**Comment by nathanielw** [comment]
@yowainwright Hi, thanks for your work on this library! I might be misunderstanding how this project is making use of Github issues, so wanted to clarify: does this issue being closed mean you/the maintainers consider it out-of-scope for the library?

Adding some more context/my view of the problem: the bug affects all browsers whenever `useFixed: true` is passed into Stickybits and all browsers that don't support `position: sticky` otherwise. I understand that Stickybits isn't aiming to be a polyfill, but preventing scroll-jumps seems reasonably critical to creating a good user experience for things like sticky navigation.

Thanks!

**Comment by yowainwright** [comment]
@nathanielw, thanks for your sentiments.

----

#### Does this issue being closed mean you consider it out-of-scope for the library?

Yes. Browsers that are over 5 years old (over 4 years old when this issue was created) are second-class citizens. "jumpy" in a 4-year-old browser was not considered broken then.

----

#### Information that may help you

- [`useGetBoundingClientRect`](https://github.com/dollarshaveclub/stickybits#stickybits-usegetboundingclientrect) might help if you want to use Stickybits. 
- This utility was written with `position: sticky` as first priority because `position: sticky` is the right CSS property for the job the Stickybtis supports. 
- This issue was opened before `useFixed` was part of the api. There were updates since this issue was created to provide support. 

----

If you would like help, please provide technical information: a Codpen, a gif, browser information, code snippets, etc. 

PRs are welcome!
