### ISSUE TITLE
Angular: useStickyClasses not working in project

### ISSUE THREAD

**Issue by cmegown** [dollarshaveclub/stickybits#145]
I'm trying to implement this (v2.0.8) in an Angular project, currently using a slightly modified version of [this directive](https://pastebin.com/wLgDd1Rn).

There are a few issues I'm seeing:
- `useStickyClasses: true` is set but do not see the classes (`.js-is-sticky/stuck`) being applied in _any_ browser
- inline styles (`position: sticky; top: 0px;`) are being applied correctly in browsers like Chrome and Firefox
- inline styles are not being applied correctly in IE 11 (only setting `top: 0px;`)

**Comment by yowainwright** [comment]
-  The `useStickyClasses: true` [example](https://codepen.io/yowainwright/pen/NpzPGR) works so we're going to have to look into why it is not working in the code you shared. 😊
-  (bullets 2& 3) In IE, `position: fixed` is added when the element is actually sticky—not immediately. 

Those things noted, can you provide an example so the community can see the issue and help?

~Thanks!

**Comment by someguynamedmatt** [comment]
@cmegown Would it be possible to get a small snippet of your Angular template that you're using stickybits with?

**Comment by cmegown** [comment]
Thanks for the rapid responses! I'll start working on a sample repo that best emulates the scenario I'm dealing with.

**Comment by AoDev** [comment]
Hello, I also don't have the classes working. It's a pure React app. 
I am implementing a listview component, similar to the ones in mobiles. (screenshot at the bottom)

The code, simplified, is like this:

- I have a wrapper that iterates over an array to create a list with sections and headers.
- the headers  should be sticky when scrolling.
- the parent is not the window, but can be any element in which the listview is placed.

__ListView component__ (import sticky Header component)
```
<div className="listview" ref={this.wrapperRef}>
  {items.map((item, index) => (
    <Section key={index}>
      <Header>
        {item.header}
      </Header>
      <Content>
        {item.content}
      </Content>
    </Section>
  ))}
</div>
```

__Header Component__ (should be sticky)

```
export default class Header extends Component {
  constructor (props) {
    super(props)
    this.getHeaderRef = this.getHeaderRef.bind(this)
  }

  componentDidMount () {
    const { headerIndex } = this.props
    this.stickyInstance = stickybits(this.headerRef, {
      stickyBitStickyOffset: headerIndex * 39,
      useStickyClasses: true
    });
  }

  componentWillUnmount () {
    this.stickyInstance.cleanup();
  }

  getHeaderRef (headerElement) {
    this.headerRef = headerElement
  }

  render () {
    return (
      <div
        className="listview__header"
        ref={this.getHeaderRef}>
        {this.props.children}
      </div>
    )
  }
}
```

<img width="489" alt="screen shot 2017-10-31 at 17 42 25" src="https://user-images.githubusercontent.com/1526150/32236582-e5d2d6ac-be62-11e7-93f9-428c1e026265.png">

<img width="1280" alt="screen shot 2017-10-31 at 17 45 52" src="https://user-images.githubusercontent.com/1526150/32236799-84ecc428-be63-11e7-9f31-6581a439e6d7.png">

As you can see, like OP, I don't have the `.js-is-sticky/stuck`  classes, but I have `js-stickybit-parent`.

__Note__: Actually it's not really that I needed the classes but I wanted to fork stickybits in order to have a hook when the element sticky state changes. (Also open it as feature request). But then I realised that the "toggleClasses" method is never called, and so, no hook possible.

**Comment by AoDev** [comment]
I have created this repo where I have the problem:  
https://github.com/AoDev/stickybits-test-case

I have tried to remove unrelated code to this issue as much as possible.

**Comment by yowainwright** [comment]
@AoDev thanks! I will look as soon as I can. 👍

**Comment by AoDev** [comment]
Thank you. I forgot to mention something:
In this app, I've copy pasted stickybits code and it's importing it. [here](https://github.com/AoDev/stickybits-test-case/blob/master/client/ui-framework/components/ListView/Header.js#L3) 

But the "original" stickybits is also in the dependencies and you can use it instead. I've just added a bunch of `console.log` in the code.

The original goal was to have __sticky and stacking__ headers. But I didn't know that the CSS sticky behaviour would "unstick" elements if there is more than one in the same container. It "unsticks" the element when the next one reaches it. -> I wanted the hook so I could do something to display stacked headers.

**Comment by yowainwright** [comment]
@donkeybonks @cyr-x could you provide an insight here in regards to Angular? 🙏

**Comment by yowainwright** [comment]
@AoDev sorry, I haven't meant to leave you hanging—did you figure anything out? 

If not, I can try to did into it a bit as time allows.

**Comment by AoDev** [comment]
@yowainwright No worries. In the end I implemented what I needed from scratch. I haven't investigated more since then. The reason being that I couldn't figure out why the behaviour of `position:sticky` is to push further any other element having also the position: sticky. So I couldn't make them stack. I'll probably open source it if my company lets me. It's a React Component implementing a listview with sticky and stackable headers.

**Comment by yowainwright** [comment]
@AoDev nice! If you do open source your project, let me know and I'll share it in the Stickybits wiki as another option.

**Comment by yowainwright** [comment]
@someguynamedmatt @majew7 I'm closing this b/c of inactivity.

**Comment by david-hollifield** [comment]
I just started trying to use this in an angular app and wasn't getting any sticky class changes either. I think the problem is due to the scroll offsets being calculated *before* the view template is being completely rendered. So the scrolling ranges aren't correct and stickybits never thinks the item is being scrolled.

**Comment by chilblane** [comment]
Yeah, I am seeing the same issue in a React app. With `useStickyClasses: true` the parent element is correctly getting a `js-stickybit-parent` but the element itself only has the inline `top: 0px; position: sticky`, and that never changes. Setting `useFixed` to `true` is essentially breaking it entirely as the only difference is the `position: sticky` inline style is removed. This means that in my React app, our fixed fallback doesn't exist.
