### ISSUE TITLE
Navigation sticks after only scrolling down 1px in IE11

### ISSUE THREAD

**Issue by glenpig** [dollarshaveclub/stickybits#289]
Hi

I have a full-width &lt;nav&gt; bar which I'm wanting to stick to the top of the browser when scrolling down.  There is a &lt;div&gt; before the &lt;nav&gt; of about 200px high but in IE11 the &lt;nav&gt; is sticking after scrolling down only 1px and not when the &lt;nav&gt; reaches the top of the browser.

Works fine in all over browsers including Edge.

Many thanks For your help

```
<script src="/assets/js/stickybits.min.js"></script>
<script>
	stickybits('.sticky-nav', {
		useStickyClasses: true
	});
</script>
```

```
<body>
	<div class-top-navbar">
	...
	</div>

	<nav class="sticky-nav">
	...
	</nav>
</body>
```

**Comment by yowainwright** [comment]
Hey @glenpig!

The code I pasted below will work. Your issue is a big reason for why Stickybits does not claim to be a polyfill. 😊 ...I code go into a deeper explanation but it might end up seeming like I'm rambling. Here's a link to the [wiki where I wrote a bit about it](https://github.com/dollarshaveclub/stickybits/wiki/Understanding-Stickybits-and-Position-Sticky)

```html
<body>
	<div class-top-navbar">
	...
	</div>
       <div class="sticky-nav-parent">
	  <nav class="sticky-nav">
	   ...
	   </nav>
        </div>
</body>
````

**Comment by yowainwright** [comment]
@glenpig I'm closing this ticket b/c on inactivity. Feel free to reach out! ~Thanks

**Comment by XavierCrespin** [comment]
Hi, i'm having a hard time getting this to work too.
Setting a parent only works if parent has a set height.
And in this situation (sticky top navbar) we cannot set a height or it will push content back on the page.

**Comment by XavierCrespin** [comment]
Fixed it by using the code from this user's pen 
https://codepen.io/adambant/pen/EQdBJd

From this thread : https://github.com/dollarshaveclub/stickybits/issues/252

**Comment by yowainwright** [comment]
@XavierCrespin would you like to submit a PR?

**Comment by XavierCrespin** [comment]
@yowainwright hey!
What should i do? i'd be glad to help but sorry i don't understand

**Comment by yowainwright** [comment]
Submit a Pull Request with the code changes you'd expect. Does that make sense? 😊

**Comment by yowainwright** [comment]
I believe/hope this issue was fixed by @ajithbhat [here](https://github.com/dollarshaveclub/stickybits/commit/e2d97785c354aea29f31f438bed745b8297fe649). 

If not, the calculations can be done as referenced [here](https://github.com/dollarshaveclub/stickybits/issues/252#issuecomment-368697539) thanks to @adambant but within @ajithbhat's `getOffsetTop` [method](https://github.com/dollarshaveclub/stickybits/blob/master/src/stickybits.js#L192).

**Comment by darekkay** [comment]
I've had a similar issue when using `.sticky-top` from [Bootstrap 4](https://getbootstrap.com/docs/4.0/utilities/position/). This class basically adds a `top: 0`. When `.js-is-stuck` is applied, `bottom: 0` is added, leading to `top: 0; bottom: 0;`, which moves the whole sticky element to the top by default. My quick solution/workaround was

```
.js-is-stuck.sticky-top: {
  top: auto;
}
```

which unsets the `top: 0` value.
