### ISSUE TITLE
js-is-sticky--change works well only when going out off sticky mode

### ISSUE THREAD

**Issue by SharakPL** [dollarshaveclub/stickybits#316]
I assume `js-is-sticky--change` class is supposed to be added the moment element stops scrolling and sticks to the top. Then when it stucks at the bottom of parent container this class is removed. This is needed to actually have element styled properly while in sticky mode. But only removing this class works well. Adding it happens always too early or too late (depends on the content of sticky element and content before it):

[https://jsfiddle.net/5gnxusbz/](https://jsfiddle.net/5gnxusbz/)

BTW you  should add info about `stickyChangeClass` to your [Custom CSS classes](https://github.com/dollarshaveclub/stickybits#stickybits-custom-css-classes)

**Comment by yowainwright** [comment]
@SharakPL:

The developer can define when the class `js-is-sticky--change` is added to a Stickybits [instance](https://github.com/dollarshaveclub/stickybits/blob/master/src/stickybits.js#L61).  

Feel free to submit a PR with "info" for `stickyChangeClass` in the README as well as write acceptance tests...which why `stickyChangeClass` hasn't been documented. Otherwise, I'll get to it soon.
