### ISSUE TITLE
Disable stickybits when screen is small?

### ISSUE THREAD

**Issue by malekascha** [dollarshaveclub/stickybits#355]
I'm working on a responsive search interface, where the user can select multiple filters from a panel. When the screen is large, I want the filter panel to stick using stickybits - this works fine. But if they zoom in or reduce the window size, causing the layout to change, then I want the filter panel to stop sticking, because it overlaps the search results. I tried using the window.onresize event and calling stickybits.cleanup() when the screen size is reduced, but it did not work. If the window starts out small I can just avoid calling stickybits, and if it gets made bigger from there I can activate stickybits. But I can't deactivate it once it's running. Is there a way to accomplish this?

**Comment by yowainwright** [comment]
@malekascha I'll need to see a code snippet or Codepen. Based on the issue you've described, `.cleanup()` should work.

**Comment by yowainwright** [comment]
## Options

Here are some options:

- Remove the inline [style](https://codepen.io/yowainwright/pen/xabYJa). 
- Using [`.cleanup()`](https://codepen.io/yowainwright/pen/JaopyZ).

----

## Why is this not done within _Stickybits_?

`.cleanup` is not provided by default because the main reason **for** Stickybits is to support stickiness! So if `position: sticky` is supported, `.cleanup` is never invoked. Stickybits adds the style `position: sticky` and does not invoke any functionality again (for performance). The `.cleanup` method provides support for when Stickybits options are used—so that it can clean stuff up **if** Stickybits methods will continue to be invoked.

**Comment by malekascha** [comment]
Thanks, Jeff!

**Comment by krodelabestiole** [comment]
hello I'm just facing the same issue, but I can't fix it.

I would like the sticky style to be totally disabled (I would have a relative positioned element) when the screen is smaller than 900px wide, but becoming sticky again when the window is bigger.

Unfortunately we cannot override the sticky positioning with CSS (an @media breakpoint would be great) for it is specified in the DOM. That would be the simplest I guess : using specific CSS rules we could override instead of DOM styles we can only deal with with JS.

Anyway this would be my code :
```
let sb = stickybits('#masthead', {useStickyClasses: true, customStickyChangeNumber:30})

function stick () {
  if (window.innerWidth < 900){
    sb.cleanup()
    document.querySelector('#masthead').style.position = 'relative'
  }
  else {
    // sb.revive() ?
  }
}
window.addEventListener('resize', () => {
  stick()
})
stick()
```
Without cleanup the position is reset to sticky at any scroll.
But I don't know how to "revive" the sticky behaviour after a cleanup.
retrying `sb = stickybits('#masthead', {useStickyClasses: true, customStickyChangeNumber:30})`
is not great : it adds infinite styles to the DOM and it doesn't work anyway.

**Comment by krodelabestiole** [comment]
@yowainwright could you please reopen ?

**Comment by yowainwright** [comment]
Hey @krodelabestiole.

I wrote this Codepen super quick...but I think [this is a solution](https://codepen.io/yowainwright/pen/Oopjbw) to the issue you posted—feel free to make something better with a debounce and post it in a comment below—but there is no reason to re-open this issue from my perspective. 

----

If you're purposing a `.revive()` method, I would like to see a use case that isn't toggling the viewport size—only people testing a feature do that. 😀...And then I'd need to get quite a few thumbs up on the feature request before I'd make it—trying to keep Stickybits a utility.

**Comment by krodelabestiole** [comment]
oh thanks for your answer !

I thought I posted one last message yesterday but I was apparently so satisfied with the preview that I din't actually posted it... :/ Here was the solution I came with :
```
let sb = stickybits('#masthead', {useStickyClasses: true, customStickyChangeNumber:30})
let sbManaged = true

function stick () {
  if (window.innerWidth < 900){
    if (sbManaged) {
      sb.cleanup()
      document.querySelector('#masthead').classList.remove('js-is-sticky--change')
    }
    sbManaged = false
  }
  else {
    if (!sbManaged) {
      sb = stickybits('#masthead', {useStickyClasses: true, customStickyChangeNumber:30})
    }
    sbManaged = true
  }
}
window.addEventListener('resize', () => {
  stick()
})
stick()
```

It's quite the same approach but I think your code is cleaner, I will adapt. Thanks again !

I'm not really proposing a revive() method. I was more trying to make my point understandable.

However what I think could be more interesting would be an option to let the user deal with the position:sticky only on the CSS side, so we could override this property with @media rules e.g.

I understand that stickybits add extra compatibility when sticky CSS option is not available, but I'm really using it only for the extra sticky classes, because there is no such as a :stuck pseudo class.
