### ISSUE TITLE
Passive scroll listener

### ISSUE THREAD

**Issue by anilanar** [dollarshaveclub/stickybits#45]
Doesn't it make more sense to use a passive scroll listener as `preventDefault()` is not used?

**Comment by yowainwright** [comment]
@anilanar, I did not know about the `passive` property but the pr looks 👌! I will look shortly 🙏

**Comment by aFarkas** [comment]
Using the `passive` event option for the scroll event doesn't make much sense. If used in conjunction with `scroll` event it only shows some basic misunderstanding of the devs writing the code.

**Comment by anilanar** [comment]
@aFarkas You are right, I assumed `scroll` was preventable, apparently it's only touch and wheel events. However if you don't mind, that bomb is more than welcome.

**Comment by aFarkas** [comment]
Thx, @anilanar. I just answered this [stackoverflow question](https://stackoverflow.com/questions/41740082/scroll-events-requestanimationframe-vs-requestidlecallback-vs-passive-event-lis) which I found after looking how many people are using this technique.

Checkout the `rAF` part. Because you are using the non useful pattern there too. (It's also related to [this one](https://github.com/dollarshaveclub/stickybits/issues/48)).

By the way you need to update `getBoundingClientRect` from time to time otherwise it can't react to other layout change like scripted widgets that influences height of the document or window resize...

**Comment by yowainwright** [comment]
@aFarkas thanks for your insights. 🤓
