### ISSUE TITLE
[help] why stickybits doesn't work?

### ISSUE THREAD

**Issue by SilencerWeb** [dollarshaveclub/stickybits#557]
I sincerely have no idea how `stickybits` works under the hood. I tried to do some things to make it work on my website but no luck.

Here is a [demo](https://stickybits-demo.netlify.com/a-story-by-dixie-from-amsterdam-netherlands/).

Scroll down to see this black square, it is supposed to be sticky block:

![image](https://user-images.githubusercontent.com/20713191/62407748-0f409e80-b5d7-11e9-93e9-5fb2e06aa5b1.png)

I tried to wrap this black square and set `position: absolute; height: 100%` to the wrapper but it didn't help. Also, I tried to add another wrapper inside the first one, that will have `position: relative; height: 100%` but it didn't help either.

Initialization: `stickybits('.social-share');` on page load.
`stickbits` was installed by npm, version — `3.6.6`

**Comment by yowainwright** [comment]
The element you want to be sticky is at the bottom of its parent so it never sticks.
![Student_Stories](https://user-images.githubusercontent.com/1074042/62486291-b8bc9700-b773-11e9-9166-bce906fbe029.png)

Your issue is great news for you b/c if you move your "sticky thing" out of its parent you don't need Stickybits and you can just use `position: sticky`. 
![Student_Stories](https://user-images.githubusercontent.com/1074042/62486404-0afdb800-b774-11e9-86d4-6989b452ff6e.png)

Hope that info is clear enough. If not, here's a short description of [`position: sticky`](https://github.com/dollarshaveclub/stickybits/wiki/Understanding-Stickybits-and-Position-Sticky).
